name: Install Nix
description: Installs nix on buildkite
author: https://github.com/uncountableinc
requirements: []
configuration:
  properties:
    extra-substituters:
      type: array
      items:
        type: string
    extra-trusted-public-keys:
      type: array
      items:
        type: string
    extra-conf:
      type: array
      items:
        type: string
    start-daemon:
      type: boolean
  additionalProperties: false
