#!/bin/bash

set -euo pipefail

echo "Installing Determinate Nix for $OSTYPE"
curl --proto '=https' --tlsv1.2 -sSf -L "https://install.determinate.systems/nix?ci=buildkite" | \
    sh -s -- install linux \
      --no-confirm \
      --init none

nohup /usr/local/bin/determinate-nixd daemon > /dev/null 2>&1 &
export NIX_REMOTE=daemon

echo "Wait for Determinate Nixd status"
while ! determinate-nixd status >/dev/null; do
    sleep 0.1
done
echo "The Nix daemon is ready!"

export PATH="/nix/var/nix/profiles/default/bin:$HOME/.nix-profile/bin:$PATH"

